//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realtek.IntraLogin.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Realtek.IntraLogin.App_GlobalResources.LanguageResource", typeof(LanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 清除 的當地語系化字串。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除 的當地語系化字串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 學歷 的當地語系化字串。
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 高中 的當地語系化字串。
        /// </summary>
        public static string HighSchool {
            get {
                return ResourceManager.GetString("HighSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應徵職務 的當地語系化字串。
        /// </summary>
        public static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應徵類別 的當地語系化字串。
        /// </summary>
        public static string JobCategory {
            get {
                return ResourceManager.GetString("JobCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 載入 的當地語系化字串。
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 姓名 的當地語系化字串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 履歷查詢 的當地語系化字串。
        /// </summary>
        public static string PageTitle_SearchResume {
            get {
                return ResourceManager.GetString("PageTitle_SearchResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 儲存 的當地語系化字串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 儲存成功 的當地語系化字串。
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 學校 的當地語系化字串。
        /// </summary>
        public static string School {
            get {
                return ResourceManager.GetString("School", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 科系 的當地語系化字串。
        /// </summary>
        public static string SchoolDept {
            get {
                return ResourceManager.GetString("SchoolDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 搜尋 的當地語系化字串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Like數量大於等於 的當地語系化字串。
        /// </summary>
        public static string SearchLikeCount {
            get {
                return ResourceManager.GetString("SearchLikeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 我的查詢 的當地語系化字串。
        /// </summary>
        public static string SearchResume_text1 {
            get {
                return ResourceManager.GetString("SearchResume_text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登入過期，請再次重新登入! 的當地語系化字串。
        /// </summary>
        public static string SessionOut {
            get {
                return ResourceManager.GetString("SessionOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 性別 的當地語系化字串。
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
    }
}
